# Copyright 2020 Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence CE GitHub Actions CI build.
# ---------------------------------------------------------------------------

name: CI Build

on:
  push:		
    branches-ignore:
    - p4-integ*
    - last-p4-*
  pull_request:
    types:
      - opened
      - committed
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage:
         - stage1
         - stage2
         - stage3
         - stage4
         - stage5
         - stage6
         - stage7
         - stage8
         - stage9
         - stage10
         - stage11
         - stage12
         - stage13

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

      # First run a simple compile and unit tests
    - name: Build
      shell: bash
      env:
        MAVEN_USER: ${{ secrets.MavenUser }}
        MAVEN_PASSWORD: ${{ secrets.MavenPassword }}
      run: |
        export DEV_ROOT=$(pwd)
        mvn --file prj/pom.xml -U --batch-mode -e -s .github/maven/synoki.xml -DskipTests clean install

      # If the build job runs successfully then run the verify stages in parallel
    - name: Verify
      shell: bash
      env:
        MAVEN_USER: ${{ secrets.MavenUser }}
        MAVEN_PASSWORD: ${{ secrets.MavenPassword }}
      run: |
        echo "Running verify ${{ matrix.stage }}"
        export DEV_ROOT=$(pwd)
        mvn --file prj/pom.xml --batch-mode -e -s .github/maven/synoki.xml -P ${{ matrix.stage }},-default,-shell,-javadoc -Doptional -Dcoherence.SkipLargeMemoryTests=true verify
    
